package SportsManagementSystem;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

public class IndoorCategories extends javax.swing.JFrame {
    
    /**
     * Creates new form IndoorCategoriesForm
     */
    public IndoorCategories() {
        initComponents();
        this.setLocationRelativeTo(null); //centre form 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        panelTitle = new javax.swing.JPanel();
        labelAppName = new javax.swing.JLabel();
        labelCloseApp = new javax.swing.JLabel();
        labelMinimizeApp = new javax.swing.JLabel();
        panelComponents = new javax.swing.JPanel();
        labelBack = new javax.swing.JLabel();
        panelSportsIndoor = new javax.swing.JTabbedPane();
        panelBasketball = new javax.swing.JPanel();
        labelBasketballImage = new javax.swing.JLabel();
        btnEnrollBasketBall = new javax.swing.JButton();
        scrollPaneBasketball = new javax.swing.JScrollPane();
        tableTimeBasketball = new javax.swing.JTable();
        labelChargeMasterBasketball = new javax.swing.JLabel();
        txtMasterNameBasketball = new javax.swing.JTextField();
        txtMistressNameBasketball = new javax.swing.JTextField();
        labelChargeMistressBasketball = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAboutBasketball = new javax.swing.JTextArea();
        labelSportBasketball = new javax.swing.JLabel();
        txtSportIdBasketball = new javax.swing.JTextField();
        panelChess = new javax.swing.JPanel();
        labelChargeMistressChess = new javax.swing.JLabel();
        labelChargeMasterChess = new javax.swing.JLabel();
        txtMasterNameChess = new javax.swing.JTextField();
        btnEnrollChess = new javax.swing.JButton();
        labelChessImage = new javax.swing.JLabel();
        txtMistressNameChess = new javax.swing.JTextField();
        scrollPaneChess = new javax.swing.JScrollPane();
        tableTimeChess = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAboutChess = new javax.swing.JTextArea();
        labelSportChess = new javax.swing.JLabel();
        txtSportIdChess = new javax.swing.JTextField();
        panelBadminton = new javax.swing.JPanel();
        labelChargeMistressBadminton = new javax.swing.JLabel();
        labelChargeMasterBadminton = new javax.swing.JLabel();
        txtMasterNameBadminton = new javax.swing.JTextField();
        btnEnrollBadminton = new javax.swing.JButton();
        labelBadmintonImage = new javax.swing.JLabel();
        txtMistressNameBadminton = new javax.swing.JTextField();
        scrollPaneBadminton = new javax.swing.JScrollPane();
        tableTimeBadminton = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAboutBadminton = new javax.swing.JTextArea();
        labelSportBadminton = new javax.swing.JLabel();
        txtSportIdBadminton = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        labelId = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Indoor Categories ");
        setBackground(new java.awt.Color(204, 204, 204));
        setBounds(new java.awt.Rectangle(0, 25, 600, 650));
        setName("indoorCateFrame"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 650));

        panelTitle.setBackground(new java.awt.Color(0, 0, 0));
        panelTitle.setPreferredSize(new java.awt.Dimension(600, 29));

        labelAppName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelAppName.setForeground(new java.awt.Color(255, 255, 255));
        labelAppName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAppName.setText("NSBM Sports Management System");

        labelCloseApp.setBackground(new java.awt.Color(255, 255, 255));
        labelCloseApp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelCloseApp.setForeground(new java.awt.Color(255, 255, 255));
        labelCloseApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCloseApp.setText("x");
        labelCloseApp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        labelCloseApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCloseAppMouseClicked(evt);
            }
        });

        labelMinimizeApp.setBackground(new java.awt.Color(255, 255, 255));
        labelMinimizeApp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelMinimizeApp.setForeground(new java.awt.Color(255, 255, 255));
        labelMinimizeApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMinimizeApp.setText("-");
        labelMinimizeApp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        labelMinimizeApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMinimizeAppMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAppName, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 256, Short.MAX_VALUE)
                .addComponent(labelMinimizeApp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCloseApp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelTitleLayout.setVerticalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(labelAppName)
                .addContainerGap())
            .addComponent(labelCloseApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelMinimizeApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelComponents.setBackground(new java.awt.Color(40, 116, 166));
        panelComponents.setPreferredSize(new java.awt.Dimension(600, 650));

        labelBack.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        labelBack.setForeground(new java.awt.Color(255, 255, 255));
        labelBack.setText("Back to Categories");
        labelBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBackMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelBackMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelBackMouseEntered(evt);
            }
        });

        panelSportsIndoor.setBackground(new java.awt.Color(204, 204, 204));
        panelSportsIndoor.setPreferredSize(new java.awt.Dimension(600, 600));

        panelBasketball.setBackground(new java.awt.Color(40, 116, 166));
        panelBasketball.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        labelBasketballImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/basketBall.jpg"))); // NOI18N
        labelBasketballImage.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));
        labelBasketballImage.setSize(new java.awt.Dimension(290, 160));

        btnEnrollBasketBall.setBackground(new java.awt.Color(204, 204, 204));
        btnEnrollBasketBall.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEnrollBasketBall.setText("Enroll");
        btnEnrollBasketBall.setFocusable(false);
        btnEnrollBasketBall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEnrollBasketBallMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEnrollBasketBallMouseEntered(evt);
            }
        });
        btnEnrollBasketBall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollBasketBallActionPerformed(evt);
            }
        });

        tableTimeBasketball.setBackground(new java.awt.Color(40, 116, 166));
        tableTimeBasketball.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tableTimeBasketball.setForeground(new java.awt.Color(255, 255, 255));
        tableTimeBasketball.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, "04:00-07:00 pm", null, "04:00-07:00 pm"}
            },
            new String [] {
                "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTimeBasketball.setEnabled(false);
        tableTimeBasketball.setRowSelectionAllowed(false);
        tableTimeBasketball.setShowHorizontalLines(false);
        tableTimeBasketball.setShowVerticalLines(false);
        tableTimeBasketball.setUpdateSelectionOnSort(false);
        scrollPaneBasketball.setViewportView(tableTimeBasketball);

        labelChargeMasterBasketball.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelChargeMasterBasketball.setForeground(new java.awt.Color(255, 255, 255));
        labelChargeMasterBasketball.setText("Master - In - Charge:");

        txtMasterNameBasketball.setEditable(false);
        txtMasterNameBasketball.setBackground(new java.awt.Color(40, 116, 166));
        txtMasterNameBasketball.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMasterNameBasketball.setForeground(new java.awt.Color(255, 255, 255));
        txtMasterNameBasketball.setText("Mr. P Thilakaratne");
        txtMasterNameBasketball.setBorder(null);
        txtMasterNameBasketball.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtMasterNameBasketball.setDragEnabled(false);
        txtMasterNameBasketball.setFocusTraversalKeysEnabled(false);
        txtMasterNameBasketball.setFocusable(false);

        txtMistressNameBasketball.setEditable(false);
        txtMistressNameBasketball.setBackground(new java.awt.Color(40, 116, 166));
        txtMistressNameBasketball.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMistressNameBasketball.setForeground(new java.awt.Color(255, 255, 255));
        txtMistressNameBasketball.setText("Ms. I Kalunaratne");
        txtMistressNameBasketball.setBorder(null);
        txtMistressNameBasketball.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMistressNameBasketball.setDragEnabled(false);
        txtMistressNameBasketball.setFocusable(false);
        txtMistressNameBasketball.setOpaque(true);

        labelChargeMistressBasketball.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelChargeMistressBasketball.setForeground(new java.awt.Color(255, 255, 255));
        labelChargeMistressBasketball.setText("Mistress - In - Charge:");

        txtAboutBasketball.setEditable(false);
        txtAboutBasketball.setBackground(new java.awt.Color(40, 116, 166));
        txtAboutBasketball.setColumns(20);
        txtAboutBasketball.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtAboutBasketball.setForeground(new java.awt.Color(255, 255, 255));
        txtAboutBasketball.setLineWrap(true);
        txtAboutBasketball.setRows(5);
        txtAboutBasketball.setText("NSBM Basketball Club is one of the main sports clubs that is fully active Having played in major inter university and cooperate tournaments such as KDU Leader’s Trophy, CIMA Sports & APIIT Sports Extravanganza, NSBM Basketball teams have garnered a solid success over the years. Becoming the Champions in 2018 KDU Leaders’ Trophy in boys category & 2019 NSBM USPORTS in both girls and boys categories can be highlighted as major achievements of the NSBM Basketball Club thus far.");
        txtAboutBasketball.setWrapStyleWord(true);
        txtAboutBasketball.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "About", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        txtAboutBasketball.setDragEnabled(false);
        txtAboutBasketball.setFocusable(false);
        jScrollPane2.setViewportView(txtAboutBasketball);

        labelSportBasketball.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelSportBasketball.setForeground(new java.awt.Color(255, 255, 255));
        labelSportBasketball.setText("Sport Id:");

        txtSportIdBasketball.setEditable(false);
        txtSportIdBasketball.setBackground(new java.awt.Color(40, 116, 166));
        txtSportIdBasketball.setForeground(new java.awt.Color(255, 255, 255));
        txtSportIdBasketball.setText("1001");
        txtSportIdBasketball.setBorder(null);
        txtSportIdBasketball.setFocusable(false);

        javax.swing.GroupLayout panelBasketballLayout = new javax.swing.GroupLayout(panelBasketball);
        panelBasketball.setLayout(panelBasketballLayout);
        panelBasketballLayout.setHorizontalGroup(
            panelBasketballLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBasketballLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelBasketballLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBasketballLayout.createSequentialGroup()
                        .addGroup(panelBasketballLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelBasketballLayout.createSequentialGroup()
                                .addComponent(labelBasketballImage, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelBasketballLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelBasketballLayout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addComponent(txtMasterNameBasketball, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelBasketballLayout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addGroup(panelBasketballLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelBasketballLayout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addComponent(txtMistressNameBasketball, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(labelChargeMasterBasketball)
                                            .addComponent(labelChargeMistressBasketball)
                                            .addGroup(panelBasketballLayout.createSequentialGroup()
                                                .addComponent(labelSportBasketball)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtSportIdBasketball, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBasketballLayout.createSequentialGroup()
                        .addComponent(scrollPaneBasketball, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
            .addGroup(panelBasketballLayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(btnEnrollBasketBall, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBasketballLayout.setVerticalGroup(
            panelBasketballLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBasketballLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelBasketballLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBasketballLayout.createSequentialGroup()
                        .addComponent(labelChargeMasterBasketball)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMasterNameBasketball, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(labelChargeMistressBasketball)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMistressNameBasketball, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelBasketballLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSportBasketball)
                            .addComponent(txtSportIdBasketball, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelBasketballImage))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPaneBasketball, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEnrollBasketBall, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        panelSportsIndoor.addTab("Basketball", panelBasketball);

        panelChess.setBackground(new java.awt.Color(40, 116, 166));
        panelChess.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelChess.setForeground(new java.awt.Color(255, 255, 255));

        labelChargeMistressChess.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelChargeMistressChess.setForeground(new java.awt.Color(255, 255, 255));
        labelChargeMistressChess.setText("Mistress - In - Charge:");

        labelChargeMasterChess.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelChargeMasterChess.setForeground(new java.awt.Color(255, 255, 255));
        labelChargeMasterChess.setText("Master - In - Charge:");

        txtMasterNameChess.setEditable(false);
        txtMasterNameChess.setBackground(new java.awt.Color(40, 116, 166));
        txtMasterNameChess.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMasterNameChess.setForeground(new java.awt.Color(255, 255, 255));
        txtMasterNameChess.setText("Mr. N Saravanapavan");
        txtMasterNameChess.setBorder(null);
        txtMasterNameChess.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMasterNameChess.setDragEnabled(false);
        txtMasterNameChess.setFocusable(false);
        txtMasterNameChess.setOpaque(true);

        btnEnrollChess.setBackground(new java.awt.Color(204, 204, 204));
        btnEnrollChess.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEnrollChess.setText("Enroll");
        btnEnrollChess.setFocusable(false);
        btnEnrollChess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEnrollChessMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEnrollChessMouseEntered(evt);
            }
        });
        btnEnrollChess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollChessActionPerformed(evt);
            }
        });

        labelChessImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chess.jpg"))); // NOI18N
        labelChessImage.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));
        labelChessImage.setSize(new java.awt.Dimension(290, 160));

        txtMistressNameChess.setEditable(false);
        txtMistressNameChess.setBackground(new java.awt.Color(40, 116, 166));
        txtMistressNameChess.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMistressNameChess.setForeground(new java.awt.Color(255, 255, 255));
        txtMistressNameChess.setText("Ms. S M K N Weerasinghe");
        txtMistressNameChess.setBorder(null);
        txtMistressNameChess.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMistressNameChess.setDragEnabled(false);
        txtMistressNameChess.setFocusable(false);
        txtMistressNameChess.setOpaque(true);

        tableTimeChess.setBackground(new java.awt.Color(40, 116, 166));
        tableTimeChess.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tableTimeChess.setForeground(new java.awt.Color(255, 255, 255));
        tableTimeChess.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "04:00-07:00 pm", null, null, ""}
            },
            new String [] {
                "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTimeChess.setEnabled(false);
        tableTimeChess.setRowSelectionAllowed(false);
        tableTimeChess.setShowHorizontalLines(false);
        tableTimeChess.setShowVerticalLines(false);
        tableTimeChess.setUpdateSelectionOnSort(false);
        scrollPaneChess.setViewportView(tableTimeChess);

        txtAboutChess.setEditable(false);
        txtAboutChess.setBackground(new java.awt.Color(40, 116, 166));
        txtAboutChess.setColumns(20);
        txtAboutChess.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtAboutChess.setForeground(new java.awt.Color(255, 255, 255));
        txtAboutChess.setLineWrap(true);
        txtAboutChess.setRows(5);
        txtAboutChess.setText("In this strategic two player game, NSBM has taken initiative to provide the students with the benefit of the chess club which proudly guide students to learn the game and provides the school level champions with resources to continue their chess career in university level");
        txtAboutChess.setWrapStyleWord(true);
        txtAboutChess.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "About", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        txtAboutChess.setDragEnabled(false);
        txtAboutChess.setFocusable(false);
        jScrollPane3.setViewportView(txtAboutChess);

        labelSportChess.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelSportChess.setForeground(new java.awt.Color(255, 255, 255));
        labelSportChess.setText("Sport Id:");

        txtSportIdChess.setEditable(false);
        txtSportIdChess.setBackground(new java.awt.Color(40, 116, 166));
        txtSportIdChess.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSportIdChess.setForeground(new java.awt.Color(255, 255, 255));
        txtSportIdChess.setText("1002");
        txtSportIdChess.setBorder(null);
        txtSportIdChess.setFocusable(false);

        javax.swing.GroupLayout panelChessLayout = new javax.swing.GroupLayout(panelChess);
        panelChess.setLayout(panelChessLayout);
        panelChessLayout.setHorizontalGroup(
            panelChessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChessLayout.createSequentialGroup()
                .addGroup(panelChessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelChessLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(btnEnrollChess, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelChessLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelChessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelChessLayout.createSequentialGroup()
                                .addComponent(labelChessImage, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelChessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelChessLayout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(txtMasterNameChess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelChessLayout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(panelChessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelChessLayout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addComponent(txtMistressNameChess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(labelChargeMasterChess)
                                            .addComponent(labelChargeMistressChess)
                                            .addGroup(panelChessLayout.createSequentialGroup()
                                                .addComponent(labelSportChess)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtSportIdChess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(panelChessLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(scrollPaneChess, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelChessLayout.setVerticalGroup(
            panelChessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChessLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelChessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelChessLayout.createSequentialGroup()
                        .addComponent(labelChargeMasterChess)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMasterNameChess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(labelChargeMistressChess)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMistressNameChess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelChessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSportChess)
                            .addComponent(txtSportIdChess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelChessImage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(scrollPaneChess, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnEnrollChess, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        panelSportsIndoor.addTab("Chess", panelChess);

        panelBadminton.setBackground(new java.awt.Color(40, 116, 166));
        panelBadminton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelBadminton.setForeground(new java.awt.Color(255, 255, 255));

        labelChargeMistressBadminton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelChargeMistressBadminton.setForeground(new java.awt.Color(255, 255, 255));
        labelChargeMistressBadminton.setText("Mistress - In - Charge:");

        labelChargeMasterBadminton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelChargeMasterBadminton.setForeground(new java.awt.Color(255, 255, 255));
        labelChargeMasterBadminton.setText("Master - In - Charge:");

        txtMasterNameBadminton.setEditable(false);
        txtMasterNameBadminton.setBackground(new java.awt.Color(40, 116, 166));
        txtMasterNameBadminton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMasterNameBadminton.setForeground(new java.awt.Color(255, 255, 255));
        txtMasterNameBadminton.setText("Mr. D Jayamanne");
        txtMasterNameBadminton.setBorder(null);
        txtMasterNameBadminton.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMasterNameBadminton.setDragEnabled(false);
        txtMasterNameBadminton.setFocusable(false);
        txtMasterNameBadminton.setOpaque(true);

        btnEnrollBadminton.setBackground(new java.awt.Color(204, 204, 204));
        btnEnrollBadminton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEnrollBadminton.setText("Enroll");
        btnEnrollBadminton.setFocusable(false);
        btnEnrollBadminton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEnrollBadmintonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEnrollBadmintonMouseEntered(evt);
            }
        });
        btnEnrollBadminton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollBadmintonActionPerformed(evt);
            }
        });

        labelBadmintonImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/badminton.jpg"))); // NOI18N
        labelBadmintonImage.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));
        labelBadmintonImage.setSize(new java.awt.Dimension(290, 160));

        txtMistressNameBadminton.setEditable(false);
        txtMistressNameBadminton.setBackground(new java.awt.Color(40, 116, 166));
        txtMistressNameBadminton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMistressNameBadminton.setForeground(new java.awt.Color(255, 255, 255));
        txtMistressNameBadminton.setText("Ms. M Weerasekara");
        txtMistressNameBadminton.setBorder(null);
        txtMistressNameBadminton.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMistressNameBadminton.setDragEnabled(false);
        txtMistressNameBadminton.setFocusable(false);
        txtMistressNameBadminton.setOpaque(true);

        tableTimeBadminton.setBackground(new java.awt.Color(40, 116, 166));
        tableTimeBadminton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tableTimeBadminton.setForeground(new java.awt.Color(255, 255, 255));
        tableTimeBadminton.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "04:00-07:00 pm", "", "04:00-07:00 pm", ""}
            },
            new String [] {
                "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTimeBadminton.setEnabled(false);
        tableTimeBadminton.setRowSelectionAllowed(false);
        tableTimeBadminton.setShowHorizontalLines(false);
        tableTimeBadminton.setShowVerticalLines(false);
        tableTimeBadminton.setUpdateSelectionOnSort(false);
        scrollPaneBadminton.setViewportView(tableTimeBadminton);

        txtAboutBadminton.setEditable(false);
        txtAboutBadminton.setBackground(new java.awt.Color(40, 116, 166));
        txtAboutBadminton.setColumns(20);
        txtAboutBadminton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtAboutBadminton.setForeground(new java.awt.Color(255, 255, 255));
        txtAboutBadminton.setLineWrap(true);
        txtAboutBadminton.setRows(5);
        txtAboutBadminton.setText("The NSBM Badminton Club is an active and a well - established sports club at NSBM with many mercantile and national level players. This club is open to undergraduates of all levels for the purpose of recreation, physical fitness and development of skills in the sport. As one of the fastest sports in the world, badminton is a great way for students to develop and improve their reflexes, hand -eye coordination, as well as mental alertness. The club represents at in-house badminton tournaments, inter university tournaments as well as other international badminton tournaments.");
        txtAboutBadminton.setWrapStyleWord(true);
        txtAboutBadminton.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "About", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        txtAboutBadminton.setDragEnabled(false);
        txtAboutBadminton.setFocusable(false);
        jScrollPane4.setViewportView(txtAboutBadminton);

        labelSportBadminton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelSportBadminton.setForeground(new java.awt.Color(255, 255, 255));
        labelSportBadminton.setText("Sport Id:");

        txtSportIdBadminton.setEditable(false);
        txtSportIdBadminton.setBackground(new java.awt.Color(40, 116, 166));
        txtSportIdBadminton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSportIdBadminton.setForeground(new java.awt.Color(255, 255, 255));
        txtSportIdBadminton.setText("1003");
        txtSportIdBadminton.setBorder(null);
        txtSportIdBadminton.setFocusable(false);

        javax.swing.GroupLayout panelBadmintonLayout = new javax.swing.GroupLayout(panelBadminton);
        panelBadminton.setLayout(panelBadmintonLayout);
        panelBadmintonLayout.setHorizontalGroup(
            panelBadmintonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBadmintonLayout.createSequentialGroup()
                .addGroup(panelBadmintonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBadmintonLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(btnEnrollBadminton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBadmintonLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelBadmintonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4)
                            .addGroup(panelBadmintonLayout.createSequentialGroup()
                                .addComponent(labelBadmintonImage, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelBadmintonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelBadmintonLayout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(txtMasterNameBadminton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelBadmintonLayout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(panelBadmintonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelBadmintonLayout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addComponent(txtMistressNameBadminton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(labelChargeMasterBadminton)
                                            .addComponent(labelChargeMistressBadminton)
                                            .addGroup(panelBadmintonLayout.createSequentialGroup()
                                                .addComponent(labelSportBadminton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtSportIdBadminton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBadmintonLayout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addComponent(scrollPaneBadminton, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        panelBadmintonLayout.setVerticalGroup(
            panelBadmintonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBadmintonLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelBadmintonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBadmintonLayout.createSequentialGroup()
                        .addComponent(labelChargeMasterBadminton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMasterNameBadminton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(labelChargeMistressBadminton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMistressNameBadminton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelBadmintonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSportBadminton)
                            .addComponent(txtSportIdBadminton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelBadmintonImage))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(scrollPaneBadminton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnEnrollBadminton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        panelSportsIndoor.addTab("Badminton", panelBadminton);

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(40, 116, 166));
        txtId.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        txtId.setBorder(null);
        txtId.setFocusable(false);

        labelId.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelId.setForeground(new java.awt.Color(255, 255, 255));
        labelId.setText("ID :");

        javax.swing.GroupLayout panelComponentsLayout = new javax.swing.GroupLayout(panelComponents);
        panelComponents.setLayout(panelComponentsLayout);
        panelComponentsLayout.setHorizontalGroup(
            panelComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComponentsLayout.createSequentialGroup()
                .addGroup(panelComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelComponentsLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(labelBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelComponentsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelSportsIndoor, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        panelComponentsLayout.setVerticalGroup(
            panelComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelComponentsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelId)
                    .addComponent(labelBack)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSportsIndoor, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelComponents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelComponents, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelCloseAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCloseAppMouseClicked
        System.exit(0); //close the app
    }//GEN-LAST:event_labelCloseAppMouseClicked

    private void labelMinimizeAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMinimizeAppMouseClicked
        this.setState(JFrame.ICONIFIED); //minimize the app
    }//GEN-LAST:event_labelMinimizeAppMouseClicked

    private void labelBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBackMouseExited
        labelBack.setForeground(new java.awt.Color(255,255,255)); //change font color of the label
    }//GEN-LAST:event_labelBackMouseExited

    private void labelBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBackMouseEntered
        labelBack.setForeground(new java.awt.Color(52, 73, 94)); //change font color of the label
    }//GEN-LAST:event_labelBackMouseEntered

    private void labelBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBackMouseClicked
        //go to category form when mouse is clicked
        Categories catf = new Categories();
        catf.txtId.setText(LogIn.jTextFieldId.getText());
        catf.setVisible(true);
        catf.pack();
        catf.setLocationRelativeTo(null);
        catf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelBackMouseClicked

    private void btnEnrollBasketBallMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnrollBasketBallMouseEntered
        btnEnrollBasketBall.setBackground(new java.awt.Color(0,153,225));
    }//GEN-LAST:event_btnEnrollBasketBallMouseEntered

    private void btnEnrollBasketBallMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnrollBasketBallMouseExited
        btnEnrollBasketBall.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_btnEnrollBasketBallMouseExited

    private void btnEnrollChessMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnrollChessMouseExited
        btnEnrollChess.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_btnEnrollChessMouseExited

    private void btnEnrollChessMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnrollChessMouseEntered
        btnEnrollChess.setBackground(new java.awt.Color(0,153,225));
    }//GEN-LAST:event_btnEnrollChessMouseEntered

    private void btnEnrollBadmintonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnrollBadmintonMouseExited
        btnEnrollBadminton.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_btnEnrollBadmintonMouseExited

    private void btnEnrollBadmintonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnrollBadmintonMouseEntered
        btnEnrollBadminton.setBackground(new java.awt.Color(0,153,225));
    }//GEN-LAST:event_btnEnrollBadmintonMouseEntered
    
    private void btnEnrollBasketBallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollBasketBallActionPerformed
        String spId = txtSportIdBasketball.getText();
        //get student id from the login textfield
        String stuId = txtId.getText();
            
        if(!Enrol.isEnrolled(spId)){
            PreparedStatement pst;
            //query to enroll the user 
            String enrollUserQuery = "INSERT INTO `Enrolled`(`StuId`, `SpId`) VALUES (?, ?)";
            
            try {
                pst = DbConnection.getConnection().prepareStatement(enrollUserQuery);
                pst.setString(1, stuId);
                pst.setString(2, spId);

                if (pst.executeUpdate() != 0){
                    //if enrolling successfull, show enroll success form
                    EnrolSuccessfull esf = new EnrolSuccessfull();
                    esf.setVisible(true);
                    esf.pack();
                    esf.setLocationRelativeTo(null);
                    esf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                }
            } catch (SQLException ex){
                    Logger.getLogger(IndoorCategories.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
    }//GEN-LAST:event_btnEnrollBasketBallActionPerformed

    private void btnEnrollChessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollChessActionPerformed
        String spId = txtSportIdChess.getText();
        //get student id from the login textfield
        String stuId = txtId.getText();
            
        if(!Enrol.isEnrolled(spId)){
            PreparedStatement pst;
            //query to enroll the user 
            String enrollUserQuery = "INSERT INTO `Enrolled`(`StuId`, `SpId`) VALUES (?, ?)";
            
            try {
                pst = DbConnection.getConnection().prepareStatement(enrollUserQuery);
                pst.setString(1, stuId);
                pst.setString(2, spId);

                if (pst.executeUpdate() != 0){
                    //if enrolling successfull, show enroll success form
                    EnrolSuccessfull esf = new EnrolSuccessfull();
                    esf.setVisible(true);
                    esf.pack();
                    esf.setLocationRelativeTo(null);
                    esf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                }
            } catch (SQLException ex){
                    Logger.getLogger(IndoorCategories.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnEnrollChessActionPerformed

    private void btnEnrollBadmintonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollBadmintonActionPerformed
        String spId = txtSportIdBadminton.getText();
        //get student id from the login textfield
        String stuId = txtId.getText();
            
        if(!Enrol.isEnrolled(spId)){
            PreparedStatement pst;
            //query to enroll the user 
            String enrollUserQuery = "INSERT INTO `Enrolled`(`StuId`, `SpId`) VALUES (?, ?)";
            
            try {
                pst = DbConnection.getConnection().prepareStatement(enrollUserQuery);
                pst.setString(1, stuId);
                pst.setString(2, spId);

                if (pst.executeUpdate() != 0){
                    //if enrolling successfull, show enroll success form
                    EnrolSuccessfull esf = new EnrolSuccessfull();
                    esf.setVisible(true);
                    esf.pack();
                    esf.setLocationRelativeTo(null);
                    esf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                }
            } catch (SQLException ex){
                    Logger.getLogger(IndoorCategories.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnEnrollBadmintonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndoorCategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndoorCategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndoorCategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndoorCategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IndoorCategories().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnrollBadminton;
    private javax.swing.JButton btnEnrollBasketBall;
    private javax.swing.JButton btnEnrollChess;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelAppName;
    private javax.swing.JLabel labelBack;
    private javax.swing.JLabel labelBadmintonImage;
    private javax.swing.JLabel labelBasketballImage;
    private javax.swing.JLabel labelChargeMasterBadminton;
    private javax.swing.JLabel labelChargeMasterBasketball;
    private javax.swing.JLabel labelChargeMasterChess;
    private javax.swing.JLabel labelChargeMistressBadminton;
    private javax.swing.JLabel labelChargeMistressBasketball;
    private javax.swing.JLabel labelChargeMistressChess;
    private javax.swing.JLabel labelChessImage;
    private javax.swing.JLabel labelCloseApp;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelMinimizeApp;
    private javax.swing.JLabel labelSportBadminton;
    private javax.swing.JLabel labelSportBasketball;
    private javax.swing.JLabel labelSportChess;
    private javax.swing.JPanel panelBadminton;
    private javax.swing.JPanel panelBasketball;
    private javax.swing.JPanel panelChess;
    private javax.swing.JPanel panelComponents;
    private javax.swing.JTabbedPane panelSportsIndoor;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JScrollPane scrollPaneBadminton;
    private javax.swing.JScrollPane scrollPaneBasketball;
    private javax.swing.JScrollPane scrollPaneChess;
    private javax.swing.JTable tableTimeBadminton;
    private javax.swing.JTable tableTimeBasketball;
    private javax.swing.JTable tableTimeChess;
    private javax.swing.JTextArea txtAboutBadminton;
    private javax.swing.JTextArea txtAboutBasketball;
    private javax.swing.JTextArea txtAboutChess;
    public static javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMasterNameBadminton;
    private javax.swing.JTextField txtMasterNameBasketball;
    private javax.swing.JTextField txtMasterNameChess;
    private javax.swing.JTextField txtMistressNameBadminton;
    private javax.swing.JTextField txtMistressNameBasketball;
    private javax.swing.JTextField txtMistressNameChess;
    private javax.swing.JTextField txtSportIdBadminton;
    private javax.swing.JTextField txtSportIdBasketball;
    private javax.swing.JTextField txtSportIdChess;
    // End of variables declaration//GEN-END:variables
}
