/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SportsManagementSystem;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

public class OutdoorCategories extends javax.swing.JFrame {

    /**
     * Creates new form OutdoorCategoriesForm
     */
    public OutdoorCategories() {
        initComponents();
        this.setLocationRelativeTo(null); //centre form 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitle = new javax.swing.JPanel();
        labelAppName = new javax.swing.JLabel();
        labelCloseApp = new javax.swing.JLabel();
        labelMinimizeApp = new javax.swing.JLabel();
        panelComponents = new javax.swing.JPanel();
        labelBack = new javax.swing.JLabel();
        panelSportsOutdoor = new javax.swing.JTabbedPane();
        panelCricket = new javax.swing.JPanel();
        labelCricketImage = new javax.swing.JLabel();
        btnEnrollCricket = new javax.swing.JButton();
        scrollPaneCricket = new javax.swing.JScrollPane();
        tableTimeCricket = new javax.swing.JTable();
        labelChargeMasterC = new javax.swing.JLabel();
        txtMasterNameC = new javax.swing.JTextField();
        txtMistressNameC = new javax.swing.JTextField();
        labelChargeMistressC = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAboutCricket = new javax.swing.JTextArea();
        txtSportIdCricket = new javax.swing.JTextField();
        labelSportCricket = new javax.swing.JLabel();
        panelRugby = new javax.swing.JPanel();
        labelChargeMistressR = new javax.swing.JLabel();
        labelChargeMasterR = new javax.swing.JLabel();
        txtMasterNameR = new javax.swing.JTextField();
        btnEnrollRugby = new javax.swing.JButton();
        labelRugbyImage = new javax.swing.JLabel();
        txtMistressNameR = new javax.swing.JTextField();
        scrollPaneRugby = new javax.swing.JScrollPane();
        tableTimeRugby = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAboutRugby = new javax.swing.JTextArea();
        txtSportIdRugby = new javax.swing.JTextField();
        labelSportRugby = new javax.swing.JLabel();
        panelSoccer = new javax.swing.JPanel();
        labelChargeMistressS = new javax.swing.JLabel();
        labelChargeMasterS = new javax.swing.JLabel();
        txtMasterNameS = new javax.swing.JTextField();
        btnEnrollSoccer = new javax.swing.JButton();
        labelSoccerImage = new javax.swing.JLabel();
        txtMistressNameS = new javax.swing.JTextField();
        scrollPaneSoccer = new javax.swing.JScrollPane();
        tableTimeSoccer = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAboutSoccer = new javax.swing.JTextArea();
        txtSportIdSoccer = new javax.swing.JTextField();
        labelSportSoccer = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        labelId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Outdoor ");
        setBackground(new java.awt.Color(40, 116, 166));
        setBounds(new java.awt.Rectangle(0, 25, 600, 650));
        setUndecorated(true);
        setResizable(false);

        panelTitle.setBackground(new java.awt.Color(0, 0, 0));
        panelTitle.setPreferredSize(new java.awt.Dimension(600, 29));

        labelAppName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelAppName.setForeground(new java.awt.Color(255, 255, 255));
        labelAppName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAppName.setText("NSBM Sports Management System");

        labelCloseApp.setBackground(new java.awt.Color(255, 255, 255));
        labelCloseApp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelCloseApp.setForeground(new java.awt.Color(255, 255, 255));
        labelCloseApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCloseApp.setText("x");
        labelCloseApp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        labelCloseApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCloseAppMouseClicked(evt);
            }
        });

        labelMinimizeApp.setBackground(new java.awt.Color(255, 255, 255));
        labelMinimizeApp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelMinimizeApp.setForeground(new java.awt.Color(255, 255, 255));
        labelMinimizeApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMinimizeApp.setText("-");
        labelMinimizeApp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        labelMinimizeApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMinimizeAppMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAppName, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                .addComponent(labelMinimizeApp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCloseApp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelTitleLayout.setVerticalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelAppName)
                .addGap(636, 636, 636))
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addGroup(panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelMinimizeApp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(labelCloseApp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelComponents.setBackground(new java.awt.Color(40, 116, 166));
        panelComponents.setForeground(new java.awt.Color(255, 255, 255));
        panelComponents.setDoubleBuffered(false);

        labelBack.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        labelBack.setForeground(new java.awt.Color(255, 255, 255));
        labelBack.setText("Back to Categories");
        labelBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBackMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelBackMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelBackMouseEntered(evt);
            }
        });

        panelSportsOutdoor.setBackground(new java.awt.Color(40, 116, 166));
        panelSportsOutdoor.setPreferredSize(new java.awt.Dimension(600, 600));

        panelCricket.setBackground(new java.awt.Color(40, 116, 166));
        panelCricket.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        labelCricketImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cricket.jpeg"))); // NOI18N
        labelCricketImage.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));
        labelCricketImage.setSize(new java.awt.Dimension(290, 160));

        btnEnrollCricket.setBackground(new java.awt.Color(204, 204, 204));
        btnEnrollCricket.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEnrollCricket.setText("Enroll");
        btnEnrollCricket.setFocusable(false);
        btnEnrollCricket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEnrollCricketMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEnrollCricketMouseEntered(evt);
            }
        });
        btnEnrollCricket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollCricketActionPerformed(evt);
            }
        });

        tableTimeCricket.setBackground(new java.awt.Color(40, 116, 166));
        tableTimeCricket.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tableTimeCricket.setForeground(new java.awt.Color(255, 255, 255));
        tableTimeCricket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"04:00-07:00 pm", null, "", "04:00-07:00 pm", ""}
            },
            new String [] {
                "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTimeCricket.setEnabled(false);
        tableTimeCricket.setRowSelectionAllowed(false);
        tableTimeCricket.setShowHorizontalLines(false);
        tableTimeCricket.setShowVerticalLines(false);
        tableTimeCricket.setUpdateSelectionOnSort(false);
        scrollPaneCricket.setViewportView(tableTimeCricket);

        labelChargeMasterC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelChargeMasterC.setForeground(new java.awt.Color(255, 255, 255));
        labelChargeMasterC.setText("Master - In - Charge:");

        txtMasterNameC.setEditable(false);
        txtMasterNameC.setBackground(new java.awt.Color(40, 116, 166));
        txtMasterNameC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMasterNameC.setForeground(new java.awt.Color(255, 255, 255));
        txtMasterNameC.setText("Mr. K T Dissanayake");
        txtMasterNameC.setBorder(null);
        txtMasterNameC.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMasterNameC.setDragEnabled(false);
        txtMasterNameC.setFocusTraversalKeysEnabled(false);
        txtMasterNameC.setFocusable(false);

        txtMistressNameC.setEditable(false);
        txtMistressNameC.setBackground(new java.awt.Color(40, 116, 166));
        txtMistressNameC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMistressNameC.setForeground(new java.awt.Color(255, 255, 255));
        txtMistressNameC.setText("Ms. ");
        txtMistressNameC.setBorder(null);
        txtMistressNameC.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMistressNameC.setDragEnabled(false);
        txtMistressNameC.setFocusable(false);
        txtMistressNameC.setOpaque(true);

        labelChargeMistressC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelChargeMistressC.setForeground(new java.awt.Color(255, 255, 255));
        labelChargeMistressC.setText("Mistress - In - Charge:");

        txtAboutCricket.setEditable(false);
        txtAboutCricket.setBackground(new java.awt.Color(40, 116, 166));
        txtAboutCricket.setColumns(20);
        txtAboutCricket.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtAboutCricket.setForeground(new java.awt.Color(255, 255, 255));
        txtAboutCricket.setLineWrap(true);
        txtAboutCricket.setRows(5);
        txtAboutCricket.setText("NSBM cricket club is one of the most pioneering sports club established at NSBM since its inception. We are prosperous club with a long tradition of nurturing talented aspiring young cricketers to be the best that they can be.\nNSBM cricket club is a friendly, vibrant and progressive cricket club that features competitive and successful players in the NSBM Green University Town. We are an inclusive and nurturing club where new players and supporters are always warmly welcomed\n");
        txtAboutCricket.setWrapStyleWord(true);
        txtAboutCricket.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "About", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        txtAboutCricket.setDragEnabled(false);
        txtAboutCricket.setFocusable(false);
        jScrollPane2.setViewportView(txtAboutCricket);

        txtSportIdCricket.setEditable(false);
        txtSportIdCricket.setBackground(new java.awt.Color(40, 116, 166));
        txtSportIdCricket.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSportIdCricket.setForeground(new java.awt.Color(255, 255, 255));
        txtSportIdCricket.setText("1004");
        txtSportIdCricket.setBorder(null);
        txtSportIdCricket.setFocusable(false);

        labelSportCricket.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelSportCricket.setForeground(new java.awt.Color(255, 255, 255));
        labelSportCricket.setText("Sport Id:");

        javax.swing.GroupLayout panelCricketLayout = new javax.swing.GroupLayout(panelCricket);
        panelCricket.setLayout(panelCricketLayout);
        panelCricketLayout.setHorizontalGroup(
            panelCricketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCricketLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelCricketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCricketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCricketLayout.createSequentialGroup()
                            .addGroup(panelCricketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelCricketLayout.createSequentialGroup()
                                    .addGap(226, 226, 226)
                                    .addComponent(btnEnrollCricket, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelCricketLayout.createSequentialGroup()
                                    .addComponent(labelCricketImage, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelCricketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelCricketLayout.createSequentialGroup()
                                            .addGap(83, 83, 83)
                                            .addComponent(txtMasterNameC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelCricketLayout.createSequentialGroup()
                                            .addGap(41, 41, 41)
                                            .addGroup(panelCricketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(panelCricketLayout.createSequentialGroup()
                                                    .addGap(42, 42, 42)
                                                    .addComponent(txtMistressNameC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(labelChargeMasterC)
                                                .addComponent(labelChargeMistressC)
                                                .addGroup(panelCricketLayout.createSequentialGroup()
                                                    .addComponent(labelSportCricket)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtSportIdCricket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGap(44, 44, 44))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCricketLayout.createSequentialGroup()
                            .addComponent(scrollPaneCricket, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)))))
        );
        panelCricketLayout.setVerticalGroup(
            panelCricketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCricketLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelCricketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCricketLayout.createSequentialGroup()
                        .addComponent(labelChargeMasterC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMasterNameC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(labelChargeMistressC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMistressNameC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelCricketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSportCricket)
                            .addComponent(txtSportIdCricket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelCricketImage, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addGap(25, 25, 25)
                .addComponent(scrollPaneCricket, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEnrollCricket, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        panelSportsOutdoor.addTab("Cricket", panelCricket);

        panelRugby.setBackground(new java.awt.Color(40, 116, 166));
        panelRugby.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        labelChargeMistressR.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelChargeMistressR.setForeground(new java.awt.Color(255, 255, 255));
        labelChargeMistressR.setText("Mistress - In - Charge:");

        labelChargeMasterR.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelChargeMasterR.setForeground(new java.awt.Color(255, 255, 255));
        labelChargeMasterR.setText("Master - In - Charge:");

        txtMasterNameR.setEditable(false);
        txtMasterNameR.setBackground(new java.awt.Color(40, 116, 166));
        txtMasterNameR.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMasterNameR.setForeground(new java.awt.Color(255, 255, 255));
        txtMasterNameR.setText("Mr. J B Dodankotuwa");
        txtMasterNameR.setBorder(null);
        txtMasterNameR.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMasterNameR.setDragEnabled(false);
        txtMasterNameR.setFocusable(false);
        txtMasterNameR.setOpaque(true);

        btnEnrollRugby.setBackground(new java.awt.Color(204, 204, 204));
        btnEnrollRugby.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEnrollRugby.setText("Enroll");
        btnEnrollRugby.setFocusable(false);
        btnEnrollRugby.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEnrollRugbyMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEnrollRugbyMouseEntered(evt);
            }
        });
        btnEnrollRugby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollRugbyActionPerformed(evt);
            }
        });

        labelRugbyImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rugby.jpeg"))); // NOI18N
        labelRugbyImage.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));
        labelRugbyImage.setSize(new java.awt.Dimension(290, 160));

        txtMistressNameR.setEditable(false);
        txtMistressNameR.setBackground(new java.awt.Color(40, 116, 166));
        txtMistressNameR.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMistressNameR.setForeground(new java.awt.Color(255, 255, 255));
        txtMistressNameR.setText("Ms. U Hettihanthri");
        txtMistressNameR.setBorder(null);
        txtMistressNameR.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMistressNameR.setDragEnabled(false);
        txtMistressNameR.setFocusable(false);
        txtMistressNameR.setOpaque(true);

        tableTimeRugby.setBackground(new java.awt.Color(40, 116, 166));
        tableTimeRugby.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tableTimeRugby.setForeground(new java.awt.Color(255, 255, 255));
        tableTimeRugby.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", null, null, "04:00-07:00 pm"}
            },
            new String [] {
                "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTimeRugby.setEnabled(false);
        tableTimeRugby.setRowSelectionAllowed(false);
        tableTimeRugby.setShowHorizontalLines(false);
        tableTimeRugby.setShowVerticalLines(false);
        tableTimeRugby.setUpdateSelectionOnSort(false);
        scrollPaneRugby.setViewportView(tableTimeRugby);

        txtAboutRugby.setEditable(false);
        txtAboutRugby.setBackground(new java.awt.Color(40, 116, 166));
        txtAboutRugby.setColumns(20);
        txtAboutRugby.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtAboutRugby.setForeground(new java.awt.Color(255, 255, 255));
        txtAboutRugby.setLineWrap(true);
        txtAboutRugby.setRows(5);
        txtAboutRugby.setText("NSBM Rugby club is one of the  most highlighted  in the university since their non-stop victories  under the NSBM name. Skipper Geshan  pethiyagoda  and his deputy Charitha  Nanayakkara leads  the squad this year while the squad of 2019 consists  around 35 determined players. Behind all these, the guidance to play a clean game and motivation to play hard is given by our master in charge Mr Baratha dodankotuwa and Ms Sulari Fernando.   ");
        txtAboutRugby.setWrapStyleWord(true);
        txtAboutRugby.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "About", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        txtAboutRugby.setDragEnabled(false);
        txtAboutRugby.setFocusable(false);
        jScrollPane3.setViewportView(txtAboutRugby);

        txtSportIdRugby.setEditable(false);
        txtSportIdRugby.setBackground(new java.awt.Color(40, 116, 166));
        txtSportIdRugby.setForeground(new java.awt.Color(255, 255, 255));
        txtSportIdRugby.setText("1005");
        txtSportIdRugby.setBorder(null);
        txtSportIdRugby.setFocusable(false);

        labelSportRugby.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelSportRugby.setForeground(new java.awt.Color(255, 255, 255));
        labelSportRugby.setText("Sport Id:");

        javax.swing.GroupLayout panelRugbyLayout = new javax.swing.GroupLayout(panelRugby);
        panelRugby.setLayout(panelRugbyLayout);
        panelRugbyLayout.setHorizontalGroup(
            panelRugbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRugbyLayout.createSequentialGroup()
                .addGroup(panelRugbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRugbyLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(btnEnrollRugby, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRugbyLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelRugbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelRugbyLayout.createSequentialGroup()
                                .addComponent(labelRugbyImage, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelRugbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelRugbyLayout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(txtMasterNameR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelRugbyLayout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(panelRugbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelRugbyLayout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addComponent(txtMistressNameR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(labelChargeMasterR)
                                            .addComponent(labelChargeMistressR)
                                            .addGroup(panelRugbyLayout.createSequentialGroup()
                                                .addComponent(labelSportRugby)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtSportIdRugby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(panelRugbyLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(scrollPaneRugby, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRugbyLayout.setVerticalGroup(
            panelRugbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRugbyLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelRugbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRugbyLayout.createSequentialGroup()
                        .addComponent(labelChargeMasterR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMasterNameR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(labelChargeMistressR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMistressNameR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelRugbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSportRugby)
                            .addComponent(txtSportIdRugby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelRugbyImage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(scrollPaneRugby, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnEnrollRugby, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        panelSportsOutdoor.addTab("Rugby", panelRugby);

        panelSoccer.setBackground(new java.awt.Color(40, 116, 166));
        panelSoccer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        labelChargeMistressS.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelChargeMistressS.setForeground(new java.awt.Color(255, 255, 255));
        labelChargeMistressS.setText("Mistress - In - Charge:");

        labelChargeMasterS.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelChargeMasterS.setForeground(new java.awt.Color(255, 255, 255));
        labelChargeMasterS.setText("Master - In - Charge:");

        txtMasterNameS.setEditable(false);
        txtMasterNameS.setBackground(new java.awt.Color(40, 116, 166));
        txtMasterNameS.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMasterNameS.setForeground(new java.awt.Color(255, 255, 255));
        txtMasterNameS.setText("Mr. M Shafraz");
        txtMasterNameS.setBorder(null);
        txtMasterNameS.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMasterNameS.setDragEnabled(false);
        txtMasterNameS.setFocusable(false);
        txtMasterNameS.setOpaque(true);

        btnEnrollSoccer.setBackground(new java.awt.Color(204, 204, 204));
        btnEnrollSoccer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEnrollSoccer.setText("Enroll");
        btnEnrollSoccer.setFocusable(false);
        btnEnrollSoccer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEnrollSoccerMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEnrollSoccerMouseEntered(evt);
            }
        });
        btnEnrollSoccer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollSoccerActionPerformed(evt);
            }
        });

        labelSoccerImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/soccer.jpeg"))); // NOI18N
        labelSoccerImage.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));
        labelSoccerImage.setSize(new java.awt.Dimension(290, 160));

        txtMistressNameS.setEditable(false);
        txtMistressNameS.setBackground(new java.awt.Color(40, 116, 166));
        txtMistressNameS.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMistressNameS.setForeground(new java.awt.Color(255, 255, 255));
        txtMistressNameS.setText("Ms. ");
        txtMistressNameS.setBorder(null);
        txtMistressNameS.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMistressNameS.setDragEnabled(false);
        txtMistressNameS.setFocusable(false);
        txtMistressNameS.setOpaque(true);

        tableTimeSoccer.setBackground(new java.awt.Color(40, 116, 166));
        tableTimeSoccer.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tableTimeSoccer.setForeground(new java.awt.Color(255, 255, 255));
        tableTimeSoccer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"04:00-07:00 p", "", "", "04:00-07:00 pm", ""}
            },
            new String [] {
                "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTimeSoccer.setEnabled(false);
        tableTimeSoccer.setRowSelectionAllowed(false);
        tableTimeSoccer.setShowHorizontalLines(false);
        tableTimeSoccer.setShowVerticalLines(false);
        tableTimeSoccer.setUpdateSelectionOnSort(false);
        scrollPaneSoccer.setViewportView(tableTimeSoccer);

        txtAboutSoccer.setEditable(false);
        txtAboutSoccer.setBackground(new java.awt.Color(40, 116, 166));
        txtAboutSoccer.setColumns(20);
        txtAboutSoccer.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtAboutSoccer.setForeground(new java.awt.Color(255, 255, 255));
        txtAboutSoccer.setLineWrap(true);
        txtAboutSoccer.setRows(5);
        txtAboutSoccer.setText("NSBM soccer club is an active club of NSBM comprises of highly competitive players with skills on par with any other university soccer player. The team had participated in several inter-university tournaments and international sport tournaments in past few years and was able bring several winning trophies to NSBM. Always NSBM soccer club strive to provide an opportunity to any NSBM undergraduate with the interest of soccer to groom them to become good soccer player to compete with any other local or international team. ");
        txtAboutSoccer.setWrapStyleWord(true);
        txtAboutSoccer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "About", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        txtAboutSoccer.setDragEnabled(false);
        txtAboutSoccer.setFocusable(false);
        jScrollPane4.setViewportView(txtAboutSoccer);

        txtSportIdSoccer.setEditable(false);
        txtSportIdSoccer.setBackground(new java.awt.Color(40, 116, 166));
        txtSportIdSoccer.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSportIdSoccer.setForeground(new java.awt.Color(255, 255, 255));
        txtSportIdSoccer.setText("1006");
        txtSportIdSoccer.setBorder(null);
        txtSportIdSoccer.setFocusable(false);

        labelSportSoccer.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelSportSoccer.setForeground(new java.awt.Color(255, 255, 255));
        labelSportSoccer.setText("Sport Id:");

        javax.swing.GroupLayout panelSoccerLayout = new javax.swing.GroupLayout(panelSoccer);
        panelSoccer.setLayout(panelSoccerLayout);
        panelSoccerLayout.setHorizontalGroup(
            panelSoccerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSoccerLayout.createSequentialGroup()
                .addGroup(panelSoccerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSoccerLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(btnEnrollSoccer, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSoccerLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelSoccerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4)
                            .addGroup(panelSoccerLayout.createSequentialGroup()
                                .addComponent(labelSoccerImage, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelSoccerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelSoccerLayout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(txtMasterNameS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelSoccerLayout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(panelSoccerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelSoccerLayout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addComponent(txtMistressNameS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(labelChargeMasterS)
                                            .addComponent(labelChargeMistressS)
                                            .addGroup(panelSoccerLayout.createSequentialGroup()
                                                .addComponent(labelSportSoccer)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtSportIdSoccer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSoccerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(scrollPaneSoccer, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        panelSoccerLayout.setVerticalGroup(
            panelSoccerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSoccerLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelSoccerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSoccerLayout.createSequentialGroup()
                        .addComponent(labelChargeMasterS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMasterNameS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(labelChargeMistressS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMistressNameS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelSoccerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSportSoccer)
                            .addComponent(txtSportIdSoccer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelSoccerImage))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(scrollPaneSoccer, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnEnrollSoccer, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        panelSportsOutdoor.addTab("Soccer", panelSoccer);

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(40, 116, 166));
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        txtId.setBorder(null);
        txtId.setFocusable(false);

        labelId.setForeground(new java.awt.Color(255, 255, 255));
        labelId.setText("ID :");

        javax.swing.GroupLayout panelComponentsLayout = new javax.swing.GroupLayout(panelComponents);
        panelComponents.setLayout(panelComponentsLayout);
        panelComponentsLayout.setHorizontalGroup(
            panelComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComponentsLayout.createSequentialGroup()
                .addGroup(panelComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelComponentsLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(labelBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelComponentsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelSportsOutdoor, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelComponentsLayout.setVerticalGroup(
            panelComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelComponentsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelId)
                    .addComponent(labelBack)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSportsOutdoor, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(panelComponents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(panelComponents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void labelCloseAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCloseAppMouseClicked
        System.exit(0); //close the app
    }//GEN-LAST:event_labelCloseAppMouseClicked

    private void labelMinimizeAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMinimizeAppMouseClicked
        this.setState(JFrame.ICONIFIED); //minimize the app
    }//GEN-LAST:event_labelMinimizeAppMouseClicked

    private void labelBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBackMouseClicked
        //go to category form when mouse is clicked
        Categories catf = new Categories();
        catf.txtId.setText(LogIn.jTextFieldId.getText());
        catf.setVisible(true);
        catf.pack();
        catf.setLocationRelativeTo(null);
        catf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelBackMouseClicked

    private void labelBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBackMouseExited
        labelBack.setForeground(new java.awt.Color(255,255,255)); //change font color of the label
    }//GEN-LAST:event_labelBackMouseExited

    private void labelBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBackMouseEntered
        labelBack.setForeground(new java.awt.Color(52, 73, 94)); //change font color of the label
    }//GEN-LAST:event_labelBackMouseEntered

    private void btnEnrollCricketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnrollCricketMouseExited
        btnEnrollCricket.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_btnEnrollCricketMouseExited

    private void btnEnrollCricketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnrollCricketMouseEntered
        btnEnrollCricket.setBackground(new java.awt.Color(0,153,225));
    }//GEN-LAST:event_btnEnrollCricketMouseEntered
  
    private void btnEnrollCricketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollCricketActionPerformed
        String spId = txtSportIdCricket.getText();
        //get student id from the login textfield
        String stuId = txtId.getText();
            
        if(!Enrol.isEnrolled(spId)){
            PreparedStatement pst;
            //query to enroll the user 
            String enrollUserQuery = "INSERT INTO `Enrolled`(`StuId`, `SpId`) VALUES (?, ?)";
            
            try {
                pst = DbConnection.getConnection().prepareStatement(enrollUserQuery);
                pst.setString(1, stuId);
                pst.setString(2, spId);

                if (pst.executeUpdate() != 0){
                    //if enrolling successfull, show enroll success form
                    EnrolSuccessfull esf = new EnrolSuccessfull();
                    esf.setVisible(true);
                    esf.pack();
                    esf.setLocationRelativeTo(null);
                    esf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                }
            } catch (SQLException ex){
                    Logger.getLogger(IndoorCategories.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnEnrollCricketActionPerformed

    private void btnEnrollRugbyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnrollRugbyMouseExited
        btnEnrollRugby.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_btnEnrollRugbyMouseExited

    private void btnEnrollRugbyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnrollRugbyMouseEntered
        btnEnrollRugby.setBackground(new java.awt.Color(0,153,225));
    }//GEN-LAST:event_btnEnrollRugbyMouseEntered

    private void btnEnrollRugbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollRugbyActionPerformed
        String spId = txtSportIdRugby.getText();
        //get student id from the login textfield
        String stuId = txtId.getText();
            
        if(!Enrol.isEnrolled(spId)){
            PreparedStatement pst;
            //query to enroll the user 
            String enrollUserQuery = "INSERT INTO `Enrolled`(`StuId`, `SpId`) VALUES (?, ?)";
            
            try {
                pst = DbConnection.getConnection().prepareStatement(enrollUserQuery);
                pst.setString(1, stuId);
                pst.setString(2, spId);

                if (pst.executeUpdate() != 0){
                    //if enrolling successfull, show enroll success form
                    EnrolSuccessfull esf = new EnrolSuccessfull();
                    esf.setVisible(true);
                    esf.pack();
                    esf.setLocationRelativeTo(null);
                    esf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                }
            } catch (SQLException ex){
                    Logger.getLogger(IndoorCategories.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnEnrollRugbyActionPerformed

    private void btnEnrollSoccerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnrollSoccerMouseExited
        btnEnrollSoccer.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_btnEnrollSoccerMouseExited

    private void btnEnrollSoccerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnrollSoccerMouseEntered
        btnEnrollSoccer.setBackground(new java.awt.Color(0,153,225));
    }//GEN-LAST:event_btnEnrollSoccerMouseEntered

    private void btnEnrollSoccerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollSoccerActionPerformed
        String spId = txtSportIdSoccer.getText();
        //get student id from the login textfield
        String stuId = txtId.getText();
            
        if(!Enrol.isEnrolled(spId)){
            PreparedStatement pst;
            //query to enroll the user 
            String enrollUserQuery = "INSERT INTO `Enrolled`(`StuId`, `SpId`) VALUES (?, ?)";
            
            try {
                pst = DbConnection.getConnection().prepareStatement(enrollUserQuery);
                pst.setString(1, stuId);
                pst.setString(2, spId);

                if (pst.executeUpdate() != 0){
                    //if enrolling successfull, show enroll success form
                    EnrolSuccessfull esf = new EnrolSuccessfull();
                    esf.setVisible(true);
                    esf.pack();
                    esf.setLocationRelativeTo(null);
                    esf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                }
            } catch (SQLException ex){
                    Logger.getLogger(IndoorCategories.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnEnrollSoccerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OutdoorCategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OutdoorCategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OutdoorCategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OutdoorCategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OutdoorCategories().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnrollCricket;
    private javax.swing.JButton btnEnrollRugby;
    private javax.swing.JButton btnEnrollSoccer;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelAppName;
    private javax.swing.JLabel labelBack;
    private javax.swing.JLabel labelChargeMasterC;
    private javax.swing.JLabel labelChargeMasterR;
    private javax.swing.JLabel labelChargeMasterS;
    private javax.swing.JLabel labelChargeMistressC;
    private javax.swing.JLabel labelChargeMistressR;
    private javax.swing.JLabel labelChargeMistressS;
    private javax.swing.JLabel labelCloseApp;
    private javax.swing.JLabel labelCricketImage;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelMinimizeApp;
    private javax.swing.JLabel labelRugbyImage;
    private javax.swing.JLabel labelSoccerImage;
    private javax.swing.JLabel labelSportCricket;
    private javax.swing.JLabel labelSportRugby;
    private javax.swing.JLabel labelSportSoccer;
    private javax.swing.JPanel panelComponents;
    private javax.swing.JPanel panelCricket;
    private javax.swing.JPanel panelRugby;
    private javax.swing.JPanel panelSoccer;
    private javax.swing.JTabbedPane panelSportsOutdoor;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JScrollPane scrollPaneCricket;
    private javax.swing.JScrollPane scrollPaneRugby;
    private javax.swing.JScrollPane scrollPaneSoccer;
    private javax.swing.JTable tableTimeCricket;
    private javax.swing.JTable tableTimeRugby;
    private javax.swing.JTable tableTimeSoccer;
    private javax.swing.JTextArea txtAboutCricket;
    private javax.swing.JTextArea txtAboutRugby;
    private javax.swing.JTextArea txtAboutSoccer;
    public static javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMasterNameC;
    private javax.swing.JTextField txtMasterNameR;
    private javax.swing.JTextField txtMasterNameS;
    private javax.swing.JTextField txtMistressNameC;
    private javax.swing.JTextField txtMistressNameR;
    private javax.swing.JTextField txtMistressNameS;
    private javax.swing.JTextField txtSportIdCricket;
    private javax.swing.JTextField txtSportIdRugby;
    private javax.swing.JTextField txtSportIdSoccer;
    // End of variables declaration//GEN-END:variables
}
