/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SportsManagementSystem;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Register extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public Register() {
        initComponents();
        this.setLocationRelativeTo(null); //centre form 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpGender = new javax.swing.ButtonGroup();
        panelTitle = new javax.swing.JPanel();
        labelAppName = new javax.swing.JLabel();
        labelCloseApp = new javax.swing.JLabel();
        labelMinimizeApp = new javax.swing.JLabel();
        panelComponents = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        labelRegForm = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        labelId = new javax.swing.JLabel();
        radioBtnMale = new javax.swing.JRadioButton();
        radioBtnFemale = new javax.swing.JRadioButton();
        labelGender = new javax.swing.JLabel();
        labelBatch = new javax.swing.JLabel();
        txtDegree = new javax.swing.JTextField();
        labelContact = new javax.swing.JLabel();
        comboBoxUni = new javax.swing.JComboBox<>();
        labelEmail = new javax.swing.JLabel();
        labelUni = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        txtBatch = new javax.swing.JTextField();
        labelDegree = new javax.swing.JLabel();
        labelPswd = new javax.swing.JLabel();
        labelRePswd = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pswdRecheckField = new javax.swing.JPasswordField();
        pswdField = new javax.swing.JPasswordField();
        labelLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registration Form");
        setBackground(new java.awt.Color(40, 116, 166));
        setBounds(new java.awt.Rectangle(0, 25, 600, 650));
        setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        setForeground(new java.awt.Color(204, 204, 204));
        setName("registerFrame"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 650));

        panelTitle.setBackground(new java.awt.Color(0, 0, 0));
        panelTitle.setPreferredSize(new java.awt.Dimension(600, 29));

        labelAppName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelAppName.setForeground(new java.awt.Color(255, 255, 255));
        labelAppName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAppName.setText("NSBM Sports Management System");

        labelCloseApp.setBackground(new java.awt.Color(255, 255, 255));
        labelCloseApp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelCloseApp.setForeground(new java.awt.Color(255, 255, 255));
        labelCloseApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCloseApp.setText("x");
        labelCloseApp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        labelCloseApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCloseAppMouseClicked(evt);
            }
        });

        labelMinimizeApp.setBackground(new java.awt.Color(255, 255, 255));
        labelMinimizeApp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelMinimizeApp.setForeground(new java.awt.Color(255, 255, 255));
        labelMinimizeApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMinimizeApp.setText("-");
        labelMinimizeApp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        labelMinimizeApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMinimizeAppMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAppName, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                .addComponent(labelMinimizeApp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCloseApp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelTitleLayout.setVerticalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelAppName)
                .addContainerGap())
            .addComponent(labelCloseApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelMinimizeApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelComponents.setBackground(new java.awt.Color(40, 116, 166));
        panelComponents.setPreferredSize(new java.awt.Dimension(600, 566));

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nsbmLogo.jpg"))); // NOI18N
        labelLogo.setSize(new java.awt.Dimension(220, 80));

        labelRegForm.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelRegForm.setForeground(new java.awt.Color(0, 51, 51));
        labelRegForm.setText("NSBM Club/Society Registration Form");

        labelName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelName.setForeground(new java.awt.Color(255, 255, 255));
        labelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelName.setText("Name with initials");

        txtName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtName.setToolTipText("ex: H.P.Y.B.Seneviratne");

        txtId.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });

        labelId.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelId.setForeground(new java.awt.Color(255, 255, 255));
        labelId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelId.setText("NSBM ID");

        btnGrpGender.add(radioBtnMale);
        radioBtnMale.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        radioBtnMale.setSelected(true);
        radioBtnMale.setText("Male");

        btnGrpGender.add(radioBtnFemale);
        radioBtnFemale.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        radioBtnFemale.setText("Female");

        labelGender.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelGender.setForeground(new java.awt.Color(255, 255, 255));
        labelGender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGender.setText("Gender");

        labelBatch.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelBatch.setForeground(new java.awt.Color(255, 255, 255));
        labelBatch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBatch.setText("Batch");

        txtDegree.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        labelContact.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelContact.setForeground(new java.awt.Color(255, 255, 255));
        labelContact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelContact.setText("Contact");

        comboBoxUni.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comboBoxUni.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Plymouth University, UK", "Victoria University, Australia", "University College Dublin, Ireland", "UGC, Approved" }));

        labelEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(255, 255, 255));
        labelEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEmail.setText("Email");

        labelUni.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelUni.setForeground(new java.awt.Color(255, 255, 255));
        labelUni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUni.setText("Affiliated University");

        txtContact.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContactKeyTyped(evt);
            }
        });

        txtEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btnRegister.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegisterMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegisterMouseEntered(evt);
            }
        });
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        txtBatch.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        labelDegree.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelDegree.setForeground(new java.awt.Color(255, 255, 255));
        labelDegree.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDegree.setText("Degree");

        labelPswd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelPswd.setForeground(new java.awt.Color(255, 255, 255));
        labelPswd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPswd.setText("Password");

        labelRePswd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelRePswd.setForeground(new java.awt.Color(255, 255, 255));
        labelRePswd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRePswd.setText("Re - enter Password");

        jSeparator1.setBackground(new java.awt.Color(0, 51, 102));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        pswdRecheckField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        pswdField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        pswdField.setToolTipText("Password should contain more than 5 characters");

        labelLogin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelLogin.setText("Have an account? LogIn");
        labelLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLoginMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelLoginMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelLoginMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelComponentsLayout = new javax.swing.GroupLayout(panelComponents);
        panelComponents.setLayout(panelComponentsLayout);
        panelComponentsLayout.setHorizontalGroup(
            panelComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComponentsLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelComponentsLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(radioBtnMale)
                        .addGap(27, 27, 27)
                        .addComponent(radioBtnFemale)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelComponentsLayout.createSequentialGroup()
                        .addGroup(panelComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelRePswd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelPswd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelContact, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelDegree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelBatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelComponentsLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelUni, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(76, 76, 76)
                        .addGroup(panelComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegister)
                            .addGroup(panelComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtDegree)
                                .addComponent(txtId, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(comboBoxUni, javax.swing.GroupLayout.Alignment.LEADING, 0, 290, Short.MAX_VALUE)
                                .addComponent(txtBatch)
                                .addComponent(txtContact)
                                .addComponent(pswdRecheckField)
                                .addComponent(pswdField, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(55, 55, 55))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelComponentsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelComponentsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelComponentsLayout.createSequentialGroup()
                        .addComponent(labelLogin)
                        .addGap(218, 218, 218))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelComponentsLayout.createSequentialGroup()
                        .addComponent(labelRegForm)
                        .addGap(136, 136, 136))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelComponentsLayout.createSequentialGroup()
                        .addComponent(labelLogo)
                        .addGap(182, 182, 182))))
        );
        panelComponentsLayout.setVerticalGroup(
            panelComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComponentsLayout.createSequentialGroup()
                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelRegForm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGender)
                    .addComponent(radioBtnMale)
                    .addComponent(radioBtnFemale))
                .addGap(18, 18, 18)
                .addGroup(panelComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDegree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDegree))
                .addGap(18, 18, 18)
                .addGroup(panelComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBatch)
                    .addComponent(txtBatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUni)
                    .addComponent(comboBoxUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelContact)
                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPswd)
                    .addComponent(pswdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRePswd)
                    .addComponent(pswdRecheckField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelLogin)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelComponents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(panelComponents, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelCloseAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCloseAppMouseClicked
        System.exit(0); //close app
    }//GEN-LAST:event_labelCloseAppMouseClicked

    private void labelMinimizeAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMinimizeAppMouseClicked
        this.setState(JFrame.ICONIFIED); //minimize app
    }//GEN-LAST:event_labelMinimizeAppMouseClicked

    private void labelLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLoginMouseClicked
        // opens login page
        LogIn login = new LogIn();
        login.setVisible(true);
        login.pack();
        login.setLocationRelativeTo(null);
        login.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelLoginMouseClicked

    private void labelLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLoginMouseEntered
        labelLogin.setForeground(new java.awt.Color(170, 183, 184)); //change font color of the label
    }//GEN-LAST:event_labelLoginMouseEntered

    private void labelLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLoginMouseExited
        labelLogin.setForeground(new java.awt.Color(0, 0, 0)); //change font color of the label
    }//GEN-LAST:event_labelLoginMouseExited

    private void btnRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseEntered
        btnRegister.setBackground(new java.awt.Color(52, 152, 219)); //change background color of the button
    }//GEN-LAST:event_btnRegisterMouseEntered

    private void btnRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseExited
        btnRegister.setBackground(new java.awt.Color(238,238,238)); //change background color of the button
    }//GEN-LAST:event_btnRegisterMouseExited

    private void txtContactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactKeyTyped
        //allow only numbers in contact
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_txtContactKeyTyped

    private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
        //allow only numbers as id
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_txtIdKeyTyped
    
    //function to verify fields
    public boolean verifyFields(){
        //get data from the text fields and assign to variables
        String id = txtId.getText();
        String name = txtName.getText();
        String degree = txtDegree.getText();
        String batch = txtBatch.getText();
        String uni = comboBoxUni.getSelectedItem().toString();
        String contact = txtContact.getText();
        String email = txtEmail.getText();
        String pswd = String.valueOf(pswdField.getPassword());
        String rePswd = String.valueOf(pswdRecheckField.getPassword());
        
        //check if fields are empty
        if(id.trim().equals("") || name.trim().equals("") || degree.trim().equals("")
                || batch.trim().equals("") || uni.trim().contains("--") || contact.trim().equals("") || email.trim().equals("")
                || pswd.trim().equals("") || rePswd.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill all the fields", "Empty Fields", 2);
            return false;
        }
        
        //check if the passwords are equal
        else if (!pswd.equals(rePswd)){
            JOptionPane.showMessageDialog(null, "Passwords doesn't match!\n \t Please re-enter", "Match Passwords", 2);
            return false;
        }
        
        else if (contact.length() > 10){
            JOptionPane.showMessageDialog(null, "Enter a valid contact");
            return false;
        }

        else{
            return true;
        }
    }
    
    //check if the ID already exist in the database
    public boolean checkId(String id){
        PreparedStatement pst;
        ResultSet rs;
        boolean id_exist = false;
        
        String query = "SELECT * FROM `Student` WHERE `Stu_Id` = ?";
        
        try {
            pst = DbConnection.getConnection().prepareStatement(query);
            pst.setString(1, id);
            rs = pst.executeQuery();
        
        
            if(rs.next()){
                id_exist = true;
                JOptionPane.showMessageDialog(null, "This ID is already registered! \n \t Please Login.", "Id is registered already", 2);
            }
        } 
        
        catch (SQLException ex) {
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id_exist;
    }
    
    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        //get data from text fields and assign to variables
        String id = txtId.getText();
        String name = txtName.getText();
        String gender = "Male";
        String degree = txtDegree.getText();
        String batch = txtBatch.getText();
        String uni = comboBoxUni.getSelectedItem().toString();
        String contact = txtContact.getText();
        String email = txtEmail.getText();
        String pswd = String.valueOf(pswdField.getPassword());
        String rePswd = String.valueOf(pswdRecheckField.getPassword());
        
        //set gender
        if(radioBtnFemale.isSelected()){
            gender = "Female";
        }
        
        // check if there are any empty fields
        if(verifyFields()){
            //check if the id already exists
            if(!checkId(id))
            {
                PreparedStatement pst;
                ResultSet rs;
                String registerUserQuery = "INSERT INTO `Student`(`Stu_Id`, `Stu_Name`, `Stu_Gender`, `Stu_Degree`, `Stu_Batch`, "
                         + " `Stu_University`, `Stu_Contact`, `Stu_Email`, `Stu_Password`) VALUES (?,?,?,?,?,?,?,?,?)";
                 
                try {
                    pst = DbConnection.getConnection().prepareStatement(registerUserQuery);
                    pst.setString(1, id);
                    pst.setString(2, name);
                    pst.setString(3, gender);
                    pst.setString(4, degree);
                    pst.setString(5, batch);
                    pst.setString(6, uni);
                    pst.setString(7, contact);
                    pst.setString(8, email);
                    pst.setString(9, pswd);
                     
                    if(pst.executeUpdate() != 0){
                        JOptionPane.showMessageDialog(null, "Registration Successfull. Please Login!");
                        LogIn login = new LogIn();
                        login.setVisible(true);
                        login.pack();
                        login.setLocationRelativeTo(null);
                        login.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        this.dispose();
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Error: Check Your Information");
                    }
                     
                } 
                catch (SQLException ex) {
                    Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                }
                 
            }
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
                
            }
        });
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrpGender;
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox<String> comboBoxUni;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelAppName;
    private javax.swing.JLabel labelBatch;
    private javax.swing.JLabel labelCloseApp;
    private javax.swing.JLabel labelContact;
    private javax.swing.JLabel labelDegree;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelGender;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelMinimizeApp;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPswd;
    private javax.swing.JLabel labelRePswd;
    private javax.swing.JLabel labelRegForm;
    private javax.swing.JLabel labelUni;
    private javax.swing.JPanel panelComponents;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JPasswordField pswdField;
    private javax.swing.JPasswordField pswdRecheckField;
    private javax.swing.JRadioButton radioBtnFemale;
    private javax.swing.JRadioButton radioBtnMale;
    private javax.swing.JTextField txtBatch;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtDegree;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
