/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SportsManagementSystem;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

public class Societies extends javax.swing.JFrame {

    /**
     * Creates new form SocietiesForm
     */
    public Societies() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelComponents = new javax.swing.JPanel();
        labelBack = new javax.swing.JLabel();
        panelClubs = new javax.swing.JTabbedPane();
        panelMusic = new javax.swing.JPanel();
        labelMusicImg = new javax.swing.JLabel();
        btnEnrollMusic = new javax.swing.JButton();
        scrollPaneBasketball = new javax.swing.JScrollPane();
        tableTimeMusic = new javax.swing.JTable();
        labelChargeMasterMusic = new javax.swing.JLabel();
        txtMasterNameMusic = new javax.swing.JTextField();
        txtMistressNameMusic = new javax.swing.JTextField();
        labelChargeMistressMusic = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAboutMusic = new javax.swing.JTextArea();
        labelSportMusic = new javax.swing.JLabel();
        txtClubIdMusic = new javax.swing.JTextField();
        panelMedia = new javax.swing.JPanel();
        labelChargeMistressMedia = new javax.swing.JLabel();
        labelChargeMasterMedia = new javax.swing.JLabel();
        txtMasterNameMedia = new javax.swing.JTextField();
        btnEnrollMedia = new javax.swing.JButton();
        labelMediaImg = new javax.swing.JLabel();
        txtMistressNameMedia = new javax.swing.JTextField();
        scrollPaneChess = new javax.swing.JScrollPane();
        tableTimeMedia = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAboutMedia = new javax.swing.JTextArea();
        labelClubMedia = new javax.swing.JLabel();
        txtClubIdMedia = new javax.swing.JTextField();
        panelLEO = new javax.swing.JPanel();
        labelChargeMistressLeo = new javax.swing.JLabel();
        labelChargeMasterLeo = new javax.swing.JLabel();
        txtMasterNameLeo = new javax.swing.JTextField();
        btnEnrollLeo = new javax.swing.JButton();
        labelLeoImg = new javax.swing.JLabel();
        txtMistressNameLeo = new javax.swing.JTextField();
        scrollPaneBadminton = new javax.swing.JScrollPane();
        tableTimeLeo = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAboutLeo = new javax.swing.JTextArea();
        labelClubLeo = new javax.swing.JLabel();
        txtClubIdLeo = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        labelId = new javax.swing.JLabel();
        panelTitle = new javax.swing.JPanel();
        labelAppName = new javax.swing.JLabel();
        labelCloseApp = new javax.swing.JLabel();
        labelMinimizeApp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panelComponents.setBackground(new java.awt.Color(40, 116, 166));
        panelComponents.setPreferredSize(new java.awt.Dimension(600, 650));

        labelBack.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        labelBack.setForeground(new java.awt.Color(255, 255, 255));
        labelBack.setText("Back to Categories");
        labelBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBackMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelBackMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelBackMouseEntered(evt);
            }
        });

        panelClubs.setBackground(new java.awt.Color(204, 204, 204));
        panelClubs.setPreferredSize(new java.awt.Dimension(600, 600));

        panelMusic.setBackground(new java.awt.Color(40, 116, 166));
        panelMusic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        labelMusicImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/music.jpg"))); // NOI18N
        labelMusicImg.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));
        labelMusicImg.setSize(new java.awt.Dimension(290, 160));

        btnEnrollMusic.setBackground(new java.awt.Color(204, 204, 204));
        btnEnrollMusic.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEnrollMusic.setText("Enroll");
        btnEnrollMusic.setFocusable(false);
        btnEnrollMusic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEnrollMusicMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEnrollMusicMouseEntered(evt);
            }
        });
        btnEnrollMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollMusicActionPerformed(evt);
            }
        });

        tableTimeMusic.setBackground(new java.awt.Color(40, 116, 166));
        tableTimeMusic.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tableTimeMusic.setForeground(new java.awt.Color(255, 255, 255));
        tableTimeMusic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, "04:00-07:00 pm", null, "04:00-07:00 pm"}
            },
            new String [] {
                "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTimeMusic.setEnabled(false);
        tableTimeMusic.setRowSelectionAllowed(false);
        tableTimeMusic.setShowHorizontalLines(false);
        tableTimeMusic.setShowVerticalLines(false);
        tableTimeMusic.setUpdateSelectionOnSort(false);
        scrollPaneBasketball.setViewportView(tableTimeMusic);

        labelChargeMasterMusic.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelChargeMasterMusic.setForeground(new java.awt.Color(255, 255, 255));
        labelChargeMasterMusic.setText("Master - In - Charge:");

        txtMasterNameMusic.setEditable(false);
        txtMasterNameMusic.setBackground(new java.awt.Color(40, 116, 166));
        txtMasterNameMusic.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMasterNameMusic.setForeground(new java.awt.Color(255, 255, 255));
        txtMasterNameMusic.setText("Mr. M Perera");
        txtMasterNameMusic.setBorder(null);
        txtMasterNameMusic.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtMasterNameMusic.setDragEnabled(false);
        txtMasterNameMusic.setFocusTraversalKeysEnabled(false);
        txtMasterNameMusic.setFocusable(false);

        txtMistressNameMusic.setEditable(false);
        txtMistressNameMusic.setBackground(new java.awt.Color(40, 116, 166));
        txtMistressNameMusic.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMistressNameMusic.setForeground(new java.awt.Color(255, 255, 255));
        txtMistressNameMusic.setText("Ms. ");
        txtMistressNameMusic.setBorder(null);
        txtMistressNameMusic.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMistressNameMusic.setDragEnabled(false);
        txtMistressNameMusic.setFocusable(false);
        txtMistressNameMusic.setOpaque(true);

        labelChargeMistressMusic.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelChargeMistressMusic.setForeground(new java.awt.Color(255, 255, 255));
        labelChargeMistressMusic.setText("Mistress - In - Charge:");

        txtAboutMusic.setEditable(false);
        txtAboutMusic.setBackground(new java.awt.Color(40, 116, 166));
        txtAboutMusic.setColumns(20);
        txtAboutMusic.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtAboutMusic.setForeground(new java.awt.Color(255, 255, 255));
        txtAboutMusic.setLineWrap(true);
        txtAboutMusic.setRows(5);
        txtAboutMusic.setText("Music club of NSBM provide opportunities for students to showcase their talents in broad range of music activities. Students of similar passion for music come together and help each other learn and develop their skills in this field. Every year, members of the club get the chance to compose NSBM Siyapath Siya Udanaya- Aurudu Theme Song, Poson Song etc. Which Promote NSBM brand name. Members also get the chance to organize and perfome in various Musical shows to showcase their talents.");
        txtAboutMusic.setWrapStyleWord(true);
        txtAboutMusic.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "About", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        txtAboutMusic.setDragEnabled(false);
        txtAboutMusic.setFocusable(false);
        jScrollPane2.setViewportView(txtAboutMusic);

        labelSportMusic.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelSportMusic.setForeground(new java.awt.Color(255, 255, 255));
        labelSportMusic.setText("Club Id:");

        txtClubIdMusic.setEditable(false);
        txtClubIdMusic.setBackground(new java.awt.Color(40, 116, 166));
        txtClubIdMusic.setForeground(new java.awt.Color(255, 255, 255));
        txtClubIdMusic.setText("1007");
        txtClubIdMusic.setBorder(null);
        txtClubIdMusic.setFocusable(false);

        javax.swing.GroupLayout panelMusicLayout = new javax.swing.GroupLayout(panelMusic);
        panelMusic.setLayout(panelMusicLayout);
        panelMusicLayout.setHorizontalGroup(
            panelMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMusicLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMusicLayout.createSequentialGroup()
                        .addComponent(labelMusicImg, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMusicLayout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(txtMasterNameMusic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelMusicLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(panelMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelMusicLayout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(txtMistressNameMusic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(labelChargeMasterMusic)
                                    .addComponent(labelChargeMistressMusic)
                                    .addGroup(panelMusicLayout.createSequentialGroup()
                                        .addComponent(labelSportMusic)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtClubIdMusic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMusicLayout.createSequentialGroup()
                        .addComponent(scrollPaneBasketball, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(panelMusicLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(panelMusicLayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(btnEnrollMusic, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelMusicLayout.setVerticalGroup(
            panelMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMusicLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMusicLayout.createSequentialGroup()
                        .addComponent(labelChargeMasterMusic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMasterNameMusic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(labelChargeMistressMusic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMistressNameMusic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSportMusic)
                            .addComponent(txtClubIdMusic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelMusicImg))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPaneBasketball, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEnrollMusic, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        panelClubs.addTab("Music club", panelMusic);

        panelMedia.setBackground(new java.awt.Color(40, 116, 166));
        panelMedia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelMedia.setForeground(new java.awt.Color(255, 255, 255));

        labelChargeMistressMedia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelChargeMistressMedia.setForeground(new java.awt.Color(255, 255, 255));
        labelChargeMistressMedia.setText("Mistress - In - Charge:");

        labelChargeMasterMedia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelChargeMasterMedia.setForeground(new java.awt.Color(255, 255, 255));
        labelChargeMasterMedia.setText("Master - In - Charge:");

        txtMasterNameMedia.setEditable(false);
        txtMasterNameMedia.setBackground(new java.awt.Color(40, 116, 166));
        txtMasterNameMedia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMasterNameMedia.setForeground(new java.awt.Color(255, 255, 255));
        txtMasterNameMedia.setText("Mr. O Sandaruwan");
        txtMasterNameMedia.setBorder(null);
        txtMasterNameMedia.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMasterNameMedia.setDragEnabled(false);
        txtMasterNameMedia.setFocusable(false);
        txtMasterNameMedia.setOpaque(true);

        btnEnrollMedia.setBackground(new java.awt.Color(204, 204, 204));
        btnEnrollMedia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEnrollMedia.setText("Enroll");
        btnEnrollMedia.setFocusable(false);
        btnEnrollMedia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEnrollMediaMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEnrollMediaMouseEntered(evt);
            }
        });
        btnEnrollMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollMediaActionPerformed(evt);
            }
        });

        labelMediaImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/media.jpg"))); // NOI18N
        labelMediaImg.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));
        labelMediaImg.setSize(new java.awt.Dimension(290, 160));

        txtMistressNameMedia.setEditable(false);
        txtMistressNameMedia.setBackground(new java.awt.Color(40, 116, 166));
        txtMistressNameMedia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMistressNameMedia.setForeground(new java.awt.Color(255, 255, 255));
        txtMistressNameMedia.setText("Ms. ");
        txtMistressNameMedia.setBorder(null);
        txtMistressNameMedia.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMistressNameMedia.setDragEnabled(false);
        txtMistressNameMedia.setFocusable(false);
        txtMistressNameMedia.setOpaque(true);

        tableTimeMedia.setBackground(new java.awt.Color(40, 116, 166));
        tableTimeMedia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tableTimeMedia.setForeground(new java.awt.Color(255, 255, 255));
        tableTimeMedia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "04:00-07:00 pm", null, null, ""}
            },
            new String [] {
                "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTimeMedia.setEnabled(false);
        tableTimeMedia.setRowSelectionAllowed(false);
        tableTimeMedia.setShowHorizontalLines(false);
        tableTimeMedia.setShowVerticalLines(false);
        tableTimeMedia.setUpdateSelectionOnSort(false);
        scrollPaneChess.setViewportView(tableTimeMedia);

        txtAboutMedia.setEditable(false);
        txtAboutMedia.setBackground(new java.awt.Color(40, 116, 166));
        txtAboutMedia.setColumns(20);
        txtAboutMedia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtAboutMedia.setForeground(new java.awt.Color(255, 255, 255));
        txtAboutMedia.setLineWrap(true);
        txtAboutMedia.setRows(5);
        txtAboutMedia.setText("NSBM Media club targets is to capture news of the many different events and activities happening at NSBM and communicate it to the NSBM audience and interested parties within the shortest time span. We have more than 100 students are members with the capacities of Photography, Videography, Sound editing, DJ operations, Live streaming, Compering current ");
        txtAboutMedia.setWrapStyleWord(true);
        txtAboutMedia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "About", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        txtAboutMedia.setDragEnabled(false);
        txtAboutMedia.setFocusable(false);
        jScrollPane3.setViewportView(txtAboutMedia);

        labelClubMedia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelClubMedia.setForeground(new java.awt.Color(255, 255, 255));
        labelClubMedia.setText("Club Id:");

        txtClubIdMedia.setEditable(false);
        txtClubIdMedia.setBackground(new java.awt.Color(40, 116, 166));
        txtClubIdMedia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtClubIdMedia.setForeground(new java.awt.Color(255, 255, 255));
        txtClubIdMedia.setText("1008");
        txtClubIdMedia.setBorder(null);
        txtClubIdMedia.setFocusable(false);

        javax.swing.GroupLayout panelMediaLayout = new javax.swing.GroupLayout(panelMedia);
        panelMedia.setLayout(panelMediaLayout);
        panelMediaLayout.setHorizontalGroup(
            panelMediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMediaLayout.createSequentialGroup()
                .addGroup(panelMediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMediaLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(btnEnrollMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMediaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelMediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMediaLayout.createSequentialGroup()
                                .addComponent(labelMediaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelMediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelMediaLayout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(txtMasterNameMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelMediaLayout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(panelMediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelMediaLayout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addComponent(txtMistressNameMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(labelChargeMasterMedia)
                                            .addComponent(labelChargeMistressMedia)
                                            .addGroup(panelMediaLayout.createSequentialGroup()
                                                .addComponent(labelClubMedia)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtClubIdMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(panelMediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelMediaLayout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(scrollPaneChess, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        panelMediaLayout.setVerticalGroup(
            panelMediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMediaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelMediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMediaLayout.createSequentialGroup()
                        .addComponent(labelChargeMasterMedia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMasterNameMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(labelChargeMistressMedia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMistressNameMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelMediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelClubMedia)
                            .addComponent(txtClubIdMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelMediaImg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(scrollPaneChess, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnEnrollMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        panelClubs.addTab("Media club", panelMedia);

        panelLEO.setBackground(new java.awt.Color(40, 116, 166));
        panelLEO.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelLEO.setForeground(new java.awt.Color(255, 255, 255));

        labelChargeMistressLeo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelChargeMistressLeo.setForeground(new java.awt.Color(255, 255, 255));
        labelChargeMistressLeo.setText("Mistress - In - Charge:");

        labelChargeMasterLeo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelChargeMasterLeo.setForeground(new java.awt.Color(255, 255, 255));
        labelChargeMasterLeo.setText("Master - In - Charge:");

        txtMasterNameLeo.setEditable(false);
        txtMasterNameLeo.setBackground(new java.awt.Color(40, 116, 166));
        txtMasterNameLeo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMasterNameLeo.setForeground(new java.awt.Color(255, 255, 255));
        txtMasterNameLeo.setText("Mr. A Sulakkhana");
        txtMasterNameLeo.setBorder(null);
        txtMasterNameLeo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMasterNameLeo.setDragEnabled(false);
        txtMasterNameLeo.setFocusable(false);
        txtMasterNameLeo.setOpaque(true);

        btnEnrollLeo.setBackground(new java.awt.Color(204, 204, 204));
        btnEnrollLeo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEnrollLeo.setText("Enroll");
        btnEnrollLeo.setFocusable(false);
        btnEnrollLeo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEnrollLeoMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEnrollLeoMouseEntered(evt);
            }
        });
        btnEnrollLeo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollLeoActionPerformed(evt);
            }
        });

        labelLeoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/leo.jpg"))); // NOI18N
        labelLeoImg.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));
        labelLeoImg.setSize(new java.awt.Dimension(290, 160));

        txtMistressNameLeo.setEditable(false);
        txtMistressNameLeo.setBackground(new java.awt.Color(40, 116, 166));
        txtMistressNameLeo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMistressNameLeo.setForeground(new java.awt.Color(255, 255, 255));
        txtMistressNameLeo.setText("Ms. S Fonseka ");
        txtMistressNameLeo.setBorder(null);
        txtMistressNameLeo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMistressNameLeo.setDragEnabled(false);
        txtMistressNameLeo.setFocusable(false);
        txtMistressNameLeo.setOpaque(true);

        tableTimeLeo.setBackground(new java.awt.Color(40, 116, 166));
        tableTimeLeo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tableTimeLeo.setForeground(new java.awt.Color(255, 255, 255));
        tableTimeLeo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "04:00-07:00 pm", "", "04:00-07:00 pm", ""}
            },
            new String [] {
                "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTimeLeo.setEnabled(false);
        tableTimeLeo.setRowSelectionAllowed(false);
        tableTimeLeo.setShowHorizontalLines(false);
        tableTimeLeo.setShowVerticalLines(false);
        tableTimeLeo.setUpdateSelectionOnSort(false);
        scrollPaneBadminton.setViewportView(tableTimeLeo);

        txtAboutLeo.setEditable(false);
        txtAboutLeo.setBackground(new java.awt.Color(40, 116, 166));
        txtAboutLeo.setColumns(20);
        txtAboutLeo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtAboutLeo.setForeground(new java.awt.Color(255, 255, 255));
        txtAboutLeo.setLineWrap(true);
        txtAboutLeo.setRows(5);
        txtAboutLeo.setText("LEO club is one of the largest and fastest growing service organizations around the world for young adults was brought up in national school of business management in the 100th year anniversary of LEO clubs. Under the guidance of Ms.Dilini Dissanayake and past district president Leo Mateesha Wanigasinghe, LEO club of NSBM was established. The very first president for the Leostic year 2017/2018 was Leo Matheesha Thilakarathne and the following years was led by Leo Sanhidi Fonseka, which was an award winning year for the LEO club of NSBM.");
        txtAboutLeo.setWrapStyleWord(true);
        txtAboutLeo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "About", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        txtAboutLeo.setDragEnabled(false);
        txtAboutLeo.setFocusable(false);
        jScrollPane4.setViewportView(txtAboutLeo);

        labelClubLeo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelClubLeo.setForeground(new java.awt.Color(255, 255, 255));
        labelClubLeo.setText("Club Id:");

        txtClubIdLeo.setEditable(false);
        txtClubIdLeo.setBackground(new java.awt.Color(40, 116, 166));
        txtClubIdLeo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtClubIdLeo.setForeground(new java.awt.Color(255, 255, 255));
        txtClubIdLeo.setText("1009");
        txtClubIdLeo.setBorder(null);
        txtClubIdLeo.setFocusable(false);

        javax.swing.GroupLayout panelLEOLayout = new javax.swing.GroupLayout(panelLEO);
        panelLEO.setLayout(panelLEOLayout);
        panelLEOLayout.setHorizontalGroup(
            panelLEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLEOLayout.createSequentialGroup()
                .addGroup(panelLEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLEOLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(btnEnrollLeo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLEOLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelLEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                            .addGroup(panelLEOLayout.createSequentialGroup()
                                .addGroup(panelLEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(scrollPaneBadminton, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelLEOLayout.createSequentialGroup()
                                        .addComponent(labelLeoImg)
                                        .addGroup(panelLEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelLEOLayout.createSequentialGroup()
                                                .addGap(80, 80, 80)
                                                .addComponent(txtMasterNameLeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panelLEOLayout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addGroup(panelLEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(panelLEOLayout.createSequentialGroup()
                                                        .addGap(42, 42, 42)
                                                        .addComponent(txtMistressNameLeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(labelChargeMasterLeo)
                                                    .addComponent(labelChargeMistressLeo)
                                                    .addGroup(panelLEOLayout.createSequentialGroup()
                                                        .addComponent(labelClubLeo)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtClubIdLeo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(17, 17, 17))
        );
        panelLEOLayout.setVerticalGroup(
            panelLEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLEOLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelLEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLEOLayout.createSequentialGroup()
                        .addComponent(labelChargeMasterLeo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMasterNameLeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(labelChargeMistressLeo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMistressNameLeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelLEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelClubLeo)
                            .addComponent(txtClubIdLeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelLeoImg))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(scrollPaneBadminton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEnrollLeo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        panelClubs.addTab("LEO club", panelLEO);

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(40, 116, 166));
        txtId.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        txtId.setBorder(null);
        txtId.setFocusable(false);

        labelId.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelId.setForeground(new java.awt.Color(255, 255, 255));
        labelId.setText("ID :");

        javax.swing.GroupLayout panelComponentsLayout = new javax.swing.GroupLayout(panelComponents);
        panelComponents.setLayout(panelComponentsLayout);
        panelComponentsLayout.setHorizontalGroup(
            panelComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComponentsLayout.createSequentialGroup()
                .addGroup(panelComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelComponentsLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(labelBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelComponentsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelClubs, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        panelComponentsLayout.setVerticalGroup(
            panelComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelComponentsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelId)
                    .addComponent(labelBack)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelClubs, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        panelTitle.setBackground(new java.awt.Color(0, 0, 0));
        panelTitle.setPreferredSize(new java.awt.Dimension(600, 29));

        labelAppName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelAppName.setForeground(new java.awt.Color(255, 255, 255));
        labelAppName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAppName.setText("NSBM Sports Management System");

        labelCloseApp.setBackground(new java.awt.Color(255, 255, 255));
        labelCloseApp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelCloseApp.setForeground(new java.awt.Color(255, 255, 255));
        labelCloseApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCloseApp.setText("x");
        labelCloseApp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        labelCloseApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCloseAppMouseClicked(evt);
            }
        });

        labelMinimizeApp.setBackground(new java.awt.Color(255, 255, 255));
        labelMinimizeApp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelMinimizeApp.setForeground(new java.awt.Color(255, 255, 255));
        labelMinimizeApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMinimizeApp.setText("-");
        labelMinimizeApp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        labelMinimizeApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMinimizeAppMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAppName, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 256, Short.MAX_VALUE)
                .addComponent(labelMinimizeApp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCloseApp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelTitleLayout.setVerticalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(labelAppName)
                .addContainerGap())
            .addComponent(labelCloseApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelMinimizeApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelComponents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelComponents, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBackMouseClicked
        //go to category form when mouse is clicked
        Categories catf = new Categories();
        catf.txtId.setText(LogIn.jTextFieldId.getText());
        catf.setVisible(true);
        catf.pack();
        catf.setLocationRelativeTo(null);
        catf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelBackMouseClicked

    private void labelBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBackMouseExited
        labelBack.setForeground(new java.awt.Color(255,255,255)); //change font color of the label
    }//GEN-LAST:event_labelBackMouseExited

    private void labelBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBackMouseEntered
        labelBack.setForeground(new java.awt.Color(52, 73, 94)); //change font color of the label
    }//GEN-LAST:event_labelBackMouseEntered

    private void btnEnrollMusicMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnrollMusicMouseExited
        btnEnrollMusic.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_btnEnrollMusicMouseExited

    private void btnEnrollMusicMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnrollMusicMouseEntered
        btnEnrollMusic.setBackground(new java.awt.Color(0,153,225));
    }//GEN-LAST:event_btnEnrollMusicMouseEntered

    private void btnEnrollMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollMusicActionPerformed
        String spId = txtClubIdMusic.getText();
        //get student id from the login textfield
        String stuId = txtId.getText();

        if(!Enrol.isEnrolled(spId)){
            PreparedStatement pst;
            //query to enroll the user
            String enrollUserQuery = "INSERT INTO `Enrolled`(`StuId`, `SpId`) VALUES (?, ?)";

            try {
                pst = DbConnection.getConnection().prepareStatement(enrollUserQuery);
                pst.setString(1, stuId);
                pst.setString(2, spId);

                if (pst.executeUpdate() != 0){
                    //if enrolling successfull, show enroll success form
                    EnrolSuccessfull esf = new EnrolSuccessfull();
                    esf.setVisible(true);
                    esf.pack();
                    esf.setLocationRelativeTo(null);
                    esf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                }
            } catch (SQLException ex){
                Logger.getLogger(IndoorCategories.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnEnrollMusicActionPerformed

    private void btnEnrollMediaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnrollMediaMouseExited
        btnEnrollMedia.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_btnEnrollMediaMouseExited

    private void btnEnrollMediaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnrollMediaMouseEntered
        btnEnrollMedia.setBackground(new java.awt.Color(0,153,225));
    }//GEN-LAST:event_btnEnrollMediaMouseEntered

    private void btnEnrollMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollMediaActionPerformed
        String spId = txtClubIdMedia.getText();
        //get student id from the login textfield
        String stuId = txtId.getText();

        if(!Enrol.isEnrolled(spId)){
            PreparedStatement pst;
            //query to enroll the user
            String enrollUserQuery = "INSERT INTO `Enrolled`(`StuId`, `SpId`) VALUES (?, ?)";

            try {
                pst = DbConnection.getConnection().prepareStatement(enrollUserQuery);
                pst.setString(1, stuId);
                pst.setString(2, spId);

                if (pst.executeUpdate() != 0){
                    //if enrolling successfull, show enroll success form
                    EnrolSuccessfull esf = new EnrolSuccessfull();
                    esf.setVisible(true);
                    esf.pack();
                    esf.setLocationRelativeTo(null);
                    esf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                }
            } catch (SQLException ex){
                Logger.getLogger(IndoorCategories.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnEnrollMediaActionPerformed

    private void btnEnrollLeoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnrollLeoMouseExited
        btnEnrollLeo.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_btnEnrollLeoMouseExited

    private void btnEnrollLeoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnrollLeoMouseEntered
        btnEnrollLeo.setBackground(new java.awt.Color(0,153,225));
    }//GEN-LAST:event_btnEnrollLeoMouseEntered

    private void btnEnrollLeoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollLeoActionPerformed
        String spId = txtClubIdLeo.getText();
        //get student id from the login textfield
        String stuId = txtId.getText();

        if(!Enrol.isEnrolled(spId)){
            PreparedStatement pst;
            //query to enroll the user
            String enrollUserQuery = "INSERT INTO `Enrolled`(`StuId`, `SpId`) VALUES (?, ?)";

            try {
                pst = DbConnection.getConnection().prepareStatement(enrollUserQuery);
                pst.setString(1, stuId);
                pst.setString(2, spId);

                if (pst.executeUpdate() != 0){
                    //if enrolling successfull, show enroll success form
                    EnrolSuccessfull esf = new EnrolSuccessfull();
                    esf.setVisible(true);
                    esf.pack();
                    esf.setLocationRelativeTo(null);
                    esf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                }
            } catch (SQLException ex){
                Logger.getLogger(IndoorCategories.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnEnrollLeoActionPerformed

    private void labelCloseAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCloseAppMouseClicked
        System.exit(0); //close the app
    }//GEN-LAST:event_labelCloseAppMouseClicked

    private void labelMinimizeAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMinimizeAppMouseClicked
        this.setState(JFrame.ICONIFIED); //minimize the app
    }//GEN-LAST:event_labelMinimizeAppMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Societies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Societies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Societies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Societies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Societies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnrollLeo;
    private javax.swing.JButton btnEnrollMedia;
    private javax.swing.JButton btnEnrollMusic;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelAppName;
    private javax.swing.JLabel labelBack;
    private javax.swing.JLabel labelChargeMasterLeo;
    private javax.swing.JLabel labelChargeMasterMedia;
    private javax.swing.JLabel labelChargeMasterMusic;
    private javax.swing.JLabel labelChargeMistressLeo;
    private javax.swing.JLabel labelChargeMistressMedia;
    private javax.swing.JLabel labelChargeMistressMusic;
    private javax.swing.JLabel labelCloseApp;
    private javax.swing.JLabel labelClubLeo;
    private javax.swing.JLabel labelClubMedia;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelLeoImg;
    private javax.swing.JLabel labelMediaImg;
    private javax.swing.JLabel labelMinimizeApp;
    private javax.swing.JLabel labelMusicImg;
    private javax.swing.JLabel labelSportMusic;
    private javax.swing.JTabbedPane panelClubs;
    private javax.swing.JPanel panelComponents;
    private javax.swing.JPanel panelLEO;
    private javax.swing.JPanel panelMedia;
    private javax.swing.JPanel panelMusic;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JScrollPane scrollPaneBadminton;
    private javax.swing.JScrollPane scrollPaneBasketball;
    private javax.swing.JScrollPane scrollPaneChess;
    private javax.swing.JTable tableTimeLeo;
    private javax.swing.JTable tableTimeMedia;
    private javax.swing.JTable tableTimeMusic;
    private javax.swing.JTextArea txtAboutLeo;
    private javax.swing.JTextArea txtAboutMedia;
    private javax.swing.JTextArea txtAboutMusic;
    private javax.swing.JTextField txtClubIdLeo;
    private javax.swing.JTextField txtClubIdMedia;
    private javax.swing.JTextField txtClubIdMusic;
    public static javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMasterNameLeo;
    private javax.swing.JTextField txtMasterNameMedia;
    private javax.swing.JTextField txtMasterNameMusic;
    private javax.swing.JTextField txtMistressNameLeo;
    private javax.swing.JTextField txtMistressNameMedia;
    private javax.swing.JTextField txtMistressNameMusic;
    // End of variables declaration//GEN-END:variables
}
